export const allTagSuggestions = [
  "React",
  "Node.js",
  "UI/UX",
  "Backend",
  "MongoDB",
  "JavaScript",
  "TypeScript",
  "GraphQL",
  "Redux",
  "CSS",
  "HTML",
  "Next.js",
  "Express",
  "Docker",
  "Kubernetes",
  "AWS",
  "Firebase",
  "Python",
  "Django",
  "Flask",
  "REST API",
  "Jest",
  "Cypress",
  "Webpack",
];

export const allLocationSuggestions = [
  "Hà Nội",
  "TP.HCM",
  "Đà Nẵng",
  "Huế",
  "Cần Thơ",
  "Hải Phòng",
  "Nha Trang",
  "Vũng Tàu",
  "Phú Quốc",
  "Quảng Ninh",
  "Bình Dương",
  "Đắk Lắk",
  "Long An",
  "Bình Thuận",
  "Gia Lai",
  "Kon Tum",
  "Thanh Hóa",
  "Ninh Bình",
  "Quảng Ngãi",
];

export const allRoleSuggestions = [
  "Frontend Developer",
  "Backend Developer",
  "Fullstack Developer",
  "UI/UX Designer",
  "Project Manager",
  "DevOps Engineer",
  "QA Engineer",
  "Data Scientist",
  "Mobile Developer",
  "System Administrator",
];

export const allStatusSuggestions = [
    "Idea",
    "In Progress",
    "Completed",
    "Cancelled",
    "Archived"
];
